// Dedicated synthetic QA stack only. No provider credentials or real AI requests.
const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert=require('node:assert/strict');
(async()=>{
 const base=process.env.QA_URL||'http://localhost:15174';
 if(new URL(base).port!=='15174') throw Error('Dedicated QA port 15174 required.');
 const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH||undefined});
 const page=await browser.newPage({viewport:{width:1440,height:1000}});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const suffix=Date.now(), title=`Chat QA ${suffix}`, version=`qa-${suffix}`;
 try {
  await page.goto(base);
  await page.getByLabel('Email',{exact:true}).waitFor();
  const setup=await page.getByLabel('Your name').count();
  if(setup)await page.getByLabel('Your name').fill('Builder QA Admin');
  await page.getByLabel('Email',{exact:true}).fill('builder-admin@example.test');
  await page.getByLabel('Password',{exact:true}).fill('Synthetic-password-2026');
  await page.getByRole('button',{name:setup?'Create account and sign in':'Sign in',exact:true}).click();
  await page.getByRole('button',{name:'User tour',exact:true}).click();
  await page.getByRole('button',{name:'Next',exact:true}).focus();await page.keyboard.press('Enter');
  await page.getByRole('heading',{name:'Choose a workspace'}).waitFor();
  await page.getByRole('button',{name:'Next',exact:true}).click();
  await page.getByRole('heading',{name:'Use the course builder'}).waitFor();
  assert(await page.getByLabel('Jump to a topic').locator('option').filter({hasText:'Configure OpenAI'}).count());
  await page.keyboard.press('Escape');
  await page.getByText('Start course builder',{exact:true}).click();
  await page.getByLabel('Workspace title',{exact:true}).fill(title);
  await page.getByRole('button',{name:'Create builder workspace'}).click();
  await page.getByRole('heading',{name:'Learning Expert',exact:true}).waitFor();
  assert.equal(await page.getByLabel('Action',{exact:true}).count(),0);
  await page.getByLabel('Message',{exact:true}).fill('Help me review this classroom course for novice instructors.');
  await page.locator('input[type=file][aria-label="Attach documents"]').setInputFiles({name:'chat-lesson.md',mimeType:'text/markdown',buffer:Buffer.from('# Synthetic lesson\n\nPractice planning.')});
  await page.getByRole('button',{name:'Remove chat-lesson.md'}).waitFor();
  await page.getByRole('button',{name:'Send',exact:true}).click();
  await page.locator('.builder-conversation').getByText('Help me review this classroom course for novice instructors.',{exact:true}).waitFor();
  await page.getByText('Your message is saved.',{exact:false}).waitFor();
  // Actual drop event into the composer, followed by attachment-only Send.
  await page.locator('.chat-composer').evaluate(el=>{
    const dt=new DataTransfer();dt.items.add(new File(['Synthetic assessment criteria.'],'assessment.txt',{type:'text/plain'}));
    el.dispatchEvent(new DragEvent('drop',{dataTransfer:dt,bubbles:true,cancelable:true}));
  });
  await page.getByRole('button',{name:'Remove assessment.txt'}).waitFor();
  await page.getByRole('button',{name:'Send',exact:true}).click();
  await page.getByText('Uploaded assessment.txt.',{exact:false}).waitFor();
  await page.getByText('Workspace details',{exact:true}).click();
  await page.getByRole('button',{name:'chat-lesson.md',exact:true}).click();
  await page.locator('.document-content').getByText('Practice planning.',{exact:true}).waitFor();
  await page.getByRole('button',{name:'Conversation',exact:true}).click();
  await page.getByText('Administration',{exact:true}).click();
  await page.getByRole('button',{name:'OpenAI settings',exact:true}).click();
  await page.getByRole('heading',{name:'Active agent instructions'}).waitFor();
  assert.equal(await page.locator('#system-prompt').count(),0);
  assert.equal(await page.getByLabel('Instructional Model',{exact:true}).count(),0);
  await page.getByRole('button',{name:'Save settings',exact:true}).click();
  await page.getByText('Settings saved.',{exact:true}).waitFor();
  await page.reload();
  await page.getByText('Administration',{exact:true}).click();
  await page.getByRole('button',{name:'OpenAI settings',exact:true}).click();
  assert.equal(await page.getByLabel('Instructional Model',{exact:true}).count(),0);
  const ref=page.getByRole('form',{name:'Upload shared reference'});
  await ref.getByLabel('Reference title').fill('Synthetic reference '+suffix);
  await ref.getByLabel('Subject area').fill('Planning');
  await ref.getByLabel('Issuing authority').fill('QA only');
  await ref.getByLabel('Reference version').fill('v1');
  await ref.getByLabel('Reference document').setInputFiles({name:'reference.txt',mimeType:'text/plain',buffer:Buffer.from('Synthetic planning evidence. No real doctrine.')});
  await page.getByRole('button',{name:'Inspect reference',exact:true}).click();
  await page.getByRole('button',{name:'Publish reference',exact:true}).click();
  await page.getByRole('button',{name:`Synthetic reference ${suffix} · v1 · Published`}).waitFor();
  await page.getByRole('form',{name:'Upload framework guidance'}).getByLabel('Model',{exact:true}).selectOption('ADDIE');
  assert.equal(await page.getByLabel('Guidance title').count(),0);
  await page.getByLabel('Version label').fill(version);
  await page.getByLabel('Guidance document').setInputFiles({name:'framework.md',mimeType:'text/markdown',buffer:Buffer.from('# Synthetic guidance\n\nTest only: require evidence and owner approval.')});
  await page.getByRole('button',{name:'Upload for inspection'}).click();
  await page.getByRole('button',{name:'Publish this guidance version'}).click();
  await page.getByRole('button',{name:`ADDIE guidance · ${version} · Published`}).waitFor();
  await page.getByRole('button',{name:'Workspaces',exact:true}).click();
  await page.getByRole('button',{name:title,exact:true}).click();
  await page.getByText('Workspace details',{exact:true}).click();
  assert.equal(await page.getByRole('button',{name:'Connect guidance'}).count(),0);
  await page.getByText(`Guidance ${version} (pinned)`,{exact:false}).waitFor();
  await page.getByText('Workspace details',{exact:true}).click();
  await page.screenshot({path:'/private/tmp/builder-chat-desktop-qa.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'Mobile overflow');
  await page.getByRole('button',{name:'User tour',exact:true}).click();
  await page.getByLabel('Jump to a topic').selectOption({label:'3. Use the course builder'});
  await page.getByRole('button',{name:'Back',exact:true}).click();
  await page.getByRole('heading',{name:'Choose a workspace'}).waitFor();
  await page.keyboard.press('Escape');
  await page.screenshot({path:'/private/tmp/builder-chat-mobile-qa.png',fullPage:true});
  const email=`member-${suffix}@example.test`;
  assert((await page.request.post(base+'/api/auth/users',{data:{name:'Chat QA Member',email,password:'Synthetic-member-2026'}})).ok());
  await page.request.post(base+'/api/auth/logout');
  await page.request.post(base+'/api/auth/login',{data:{email,password:'Synthetic-member-2026'}});
  await page.request.post(base+'/api/auth/password',{data:{old_password:'Synthetic-member-2026',new_password:'Synthetic-member-updated'}});
  await page.request.post(base+'/api/auth/login',{data:{email,password:'Synthetic-member-updated'}});
  await page.reload();
  await page.getByRole('button',{name:'User tour',exact:true}).click();
  assert.equal(await page.getByLabel('Jump to a topic').locator('option').filter({hasText:'Configure OpenAI'}).count(),0);
  await page.getByRole('button',{name:'Close user tour'}).click();
  await page.getByText('Start course builder',{exact:true}).click();
  await page.getByLabel('Workspace title',{exact:true}).fill(`Member chat ${suffix}`);
  await page.getByRole('button',{name:'Create builder workspace'}).click();
  await page.getByRole('heading',{name:'Learning Expert',exact:true}).waitFor();
  assert.equal(await page.getByText('Administration',{exact:true}).count(),0);
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  assert.deepEqual(errors,[]);
  console.log('PASS: single Send, attachments and drag/drop, chat guidance without framework, source reading, automatic framework connection, admin/member creation, tour keyboard/role variants, mobile layout, active instructions, settings persistence and reference publishing. No AI calls.');
 } catch(e){await page.screenshot({path:'/private/tmp/builder-chat-error-qa.png',fullPage:true});throw e;}
 finally{await browser.close();}
})().catch(e=>{console.error(e);process.exit(1)});
